version: '3'

services:
  dev:
    build:
      context:  ./
      dockerfile: Dockerfile
    environment:
      - "AWS_DEFAULT_REGION=${AWS_REGION:-us-east-1}"
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
      - "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}"
      - "AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN}"
